source("http://bioconductor.org/biocLite.R")
#biocLite()
biocLite(c("GenomicRanges", "BSgenome.Hsapiens.UCSC.hg19"), ask=FALSE)
install.packages("devtools", dependencies = TRUE)
install.packages("ggplot2", dependencies = TRUE)
install.packages("Rcpp", dependencies = TRUE)
install.packages("rjson", dependencies = TRUE)
library(devtools)
devtools::install_github("friend1ws/pmsignature")
